Modify hardening guide and add self assessment guide for cis-1.6
rancher/rke2 pull request #1051
Opened 2021-05-24 21:51 UTC by MonzElmasry

#### Proposed Changes ####
Modify hardening guide and add self assessment guide for cis-1.6

#### Types of Changes ####
Docs

#### Verification ####
N/A
#### Linked Issues ####

https://github.com/rancher/rke2/issues/876

2021-05-24 21:55 UTC, briandowns approved these changes

2021-05-24 23:03 UTC, brandond requested changes

2021-05-24 23:03 UTC, brandond commented on docs/security/hardening_guide.md
> +For more detail about evaluating a hardened cluster against the official CIS benchmark, refer to the CIS Benchmark Rancher Self-Assessment Guide [v1.5](cis_self_assessment15.md) or [v1.6](cis_self_as
I believe the links targets need to not have the .md extension on the end.

2021-05-25 20:18 UTC, brandond approved these changes

2021-05-25 20:18 UTC, brandond commented on docs/security/hardening_guide.md
> +For more detail about evaluating a hardened cluster against the official CIS benchmark, refer to the CIS Benchmark Rancher Self-Assessment Guide [v1.5](cis_self_assessment15.md) or [v1.6](cis_self_as
disregard - mkdocs should handle this correctly.

2021-05-26 16:27 UTC, merged