Fail to deploy if nm-setup-cloud is enabled
rancher/rke2 pull request #1149
Opened 2021-06-16 12:14 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

#### Proposed Changes ####

Even though we are documenting that nm-cloud-setup service breaks the rke2 cluster, it is a good idea to verify this when starting the rke2 service and not allow it to start if the user forgot to disable that service. If the OS is not running systemd, it will deploy rke2.

This PR also documents this as a known issue

#### Types of Changes ####

New feature. Prevents rke2 server or agent to start if nm-setup-cloud exists

#### Verification ####

Deploy RHEL8.4 which use nm-cloud-setup by default and run k3s. It should fail to start with the following log in journactl:
```
sh[1118717]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
sh[1118717]: + exit 1
```
#### Linked Issues ####

https://github.com/rancher/rke2/issues/1053

2021-06-16 18:20 UTC, brandond requested changes
LGTM, but I think you can negate the test more simply

2021-06-16 18:20 UTC, brandond commented on bundle/lib/systemd/system/rke2-agent.service
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
```suggestion
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
```

2021-06-16 18:20 UTC, brandond commented on bundle/lib/systemd/system/rke2-server.service
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
```suggestion
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
```

2021-06-17 10:20 UTC, manuelbuil commented on bundle/lib/systemd/system/rke2-agent.service
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
great idea! Thanks Brad

2021-06-17 10:37 UTC, brandond approved these changes

2021-06-17 13:43 UTC, briandowns approved these changes

2021-06-18 09:38 UTC, merged