Hardned k8s 119
rancher/rke2 pull request #1328
Opened 2021-07-14 23:00 UTC by luthermonson

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####
https://github.com/rancher/rke2/issues/1323
https://github.com/rancher/rke2/issues/1313

#### Further Comments ####

2021-07-14 23:37 UTC, brandond approved these changes

2021-07-14 23:38 UTC, brandond commented
LGTM, expecting CI to pass once the hardened images are tagged and built.

2021-07-15 04:16 UTC, brandond requested changes

2021-07-15 04:16 UTC, brandond commented on scripts/build-binary
> +        -X ${RKE2_PKG}/pkg/images.DefaultCloudControllerManagerImage=rancher/rke2-cloud-provider:${CCM_VERSION}
I don't think we have this here

2021-07-15 04:16 UTC, brandond commented on scripts/build-images
> +xargs -n1 -t docker image pull --quiet << EOF > build/images-canal.txt
Don't need any of the CNI or before bundles on this branch

2021-07-15 22:27 UTC, briandowns approved these changes

2021-07-15 22:28 UTC, merged