Update the documentation for Windows
rancher/rke2 pull request #1493
Opened 2021-07-29 23:23 UTC by rosskirkpat

#### Proposed Changes ####

Update the documentation for Windows

Move `docs/install/uninstall.md` to `docs/install/linux_uninstall.md`
Update mkdocs.yml to reflect new changes
Fixes an issue with bad download links for `install.ps1`
Introduce docs for the new Windows uninstall script, which is currently under review in https://github.com/rancher/rke2/pull/1488

#### Types of Changes ####

Docs changes only

#### Verification ####

Tested locally w/ `make mkdocs` and `make serve-docs` with no errors

#### Linked Issues ####

https://github.com/rancher/rke2/issues/1492

2021-07-30 00:00 UTC, brandond requested changes

2021-07-30 00:00 UTC, brandond commented on docs/install/windows_airgap.md
> +**Windows Support requires choosing Calico as the CNI for the RKE2 cluster as of v1.21.3+rke2r1**
and here

2021-07-30 14:50 UTC, rosskirkpat commented on docs/install/install_options/windows_agent_config.md
> +**Windows Support requires choosing Calico as the CNI for the RKE2 cluster as of v1.21.3+rke2r1**
Fixing this

2021-08-02 15:50 UTC, phillipsj approved these changes
LGTM

2021-08-02 15:51 UTC, luthermonson approved these changes

2021-08-02 15:52 UTC, merged