Added gotest templates, changed unit test naming
rancher/rke2 pull request #1621
Opened 2021-08-12 20:01 UTC by dereknola

Signed-off-by: Derek Nola <derek.nola@suse.com>

#### Proposed Changes ####
Copied the custom gotests templates from k3s into rke2. 
Renamed the existing unit tests to match Test_Unit<FUNCTION> style.
Added new unit test for images package... small codecov improvement.

#### Types of Changes ####
Testing

#### Verification ####
N/A

#### Linked Issues ####
https://github.com/rancher/rke2/issues/1611

#### Further Comments ####

2021-08-12 20:21 UTC, briandowns approved these changes

2021-08-12 21:53 UTC, brandond approved these changes

2021-08-13 09:37 UTC, vadorovsky approved these changes

2021-08-13 09:42 UTC, vadorovsky requested changes

2021-08-13 09:42 UTC, vadorovsky commented on pkg/images/images_test.go
> +var testDefaultImages Images
The type `Images` doesn't seem to exist in this package. See the CI error:

https://drone-pr.rancher.io/rancher/rke2/2021/1/2

2021-08-16 15:57 UTC, merged