Add release checklist
rancher/rke2 pull request #1797
Opened 2021-09-10 16:13 UTC by briandowns

Signed-off-by: Brian Downs <brian.downs@gmail.com>

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2021-09-10 16:14 UTC, manuelbuil approved these changes

2021-09-10 17:25 UTC, brandond requested changes

2021-09-10 17:25 UTC, brandond commented on developer-docs/upgrading_kubernetes.md
> +- [ ] Tag RKE2 packaging release "stable"
```suggestion
- [ ] Add release notes to release
- [ ] Tag RKE2 packaging release "testing"
- [ ] Tag RKE2 packaging release "latest"
- [ ] Uncheck "pre-release"
- [ ] Wait 1 week for community to report issues
- [ ] Tag RKE2 packaging release "stable"
- [ ] Update stable release in channels.yaml
- [ ] Update KDM
```

2021-09-10 17:58 UTC, brandond approved these changes

2021-09-10 20:00 UTC, dweomer approved these changes
LGTM

We should capture this in a issue template like we do for k3s, no?
See https://github.com/k3s-io/k3s/blob/master/.github/ISSUE_TEMPLATE/cut_release.md

2021-09-10 20:05 UTC, briandowns commented
> LGTM
> 
> We should capture this in a issue template like we do for k3s, no?
> See https://github.com/k3s-io/k3s/blob/master/.github/ISSUE_TEMPLATE/cut_release.md

Yeah, I could probably get this going next week.

2021-09-13 16:38 UTC, dereknola approved these changes

2021-09-15 16:53 UTC, cwayne18 commented
Yeah, I think this would be better as an issue template, that's on me for not creating it in the first place.  I think part of the reasoning was that it needed to be different than k3s due to stuff like releasing rpm's, marking them stable, etc.

2021-09-15 17:04 UTC, briandowns commented
Would you want this repurposed as a procedural outline in the docs?

2021-09-15 17:07 UTC, cwayne18 commented
I think that would make sense

2021-09-15 19:41 UTC, merged