Documented that snapshots are handled differently for RKE2 clusters
rancher/rke2 pull request #1813
Opened 2021-09-13 21:00 UTC by jtravee

As referenced in Rancher/docs https://github.com/rancher/docs/issues/3494 and dashboard https://github.com/rancher/dashboard/issues/4081.

2021-09-13 21:07 UTC, briandowns approved these changes

2021-09-13 22:08 UTC, brandond requested changes

2021-09-13 22:08 UTC, brandond commented on docs/backup_restore.md
> +In RKE2, snapshots are stored on each etcd node.
```suggestion
In RKE2, snapshots are stored on each etcd node. If you have multiple etcd or etcd + control-plane nodes, you will have multiple copies of local etcd snapshots.
```

2021-09-14 17:04 UTC, brandond approved these changes

2021-09-14 17:04 UTC, merged