Add QA Release info to  release docs
rancher/rke2 pull request #1825
Opened 2021-09-15 16:03 UTC by dereknola

Signed-off-by: dereknola <derek.nola@suse.com>

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2021-09-15 16:21 UTC, brandond requested changes

2021-09-15 16:21 UTC, brandond commented on developer-docs/upgrading_kubernetes.md
> +a tag should be cut for v1.20.10-rc1+rke2r2 release.
```suggestion
a tag should be cut for v1.20.10-rc1+rke2r2 release. Note that doing so will also require tagging v1.20.10+rke2r2
in image-build-kubernetes and bumping versions across rke2-charts and rke2, as if preparing for a full release.
```

2021-09-15 17:43 UTC, brandond approved these changes

2021-09-16 18:28 UTC, briandowns approved these changes

2021-09-16 18:29 UTC, merged