Documented improvements to RKE2 Etcd Backup and Restore Docs
rancher/rke2 pull request #2073
Opened 2021-11-01 15:41 UTC by jtravee

Closes https://github.com/rancher/docs/issues/3613 in rancher/docs.

1. Documented new step-by-step guides for restore to new & existing nodes.

Reference: https://docs.rke2.io/backup_restore/

2021-11-01 22:10 UTC, brandond requested changes
LGTM; one nit on flag consistency

2021-11-01 22:10 UTC, brandond commented on docs/backup_restore.md
> + --cluster-reset-restore-path=<PATH-TO-SNAPSHOT> --token <token used in the original cluster>
```suggestion
 --cluster-reset-restore-path=<PATH-TO-SNAPSHOT> \
 --token=<token used in the original cluster>
```

2021-11-02 13:19 UTC, jtravee commented on docs/backup_restore.md
> + --cluster-reset-restore-path=<PATH-TO-SNAPSHOT> --token <token used in the original cluster>
Thanks!

2021-11-02 15:59 UTC, brandond approved these changes

2021-11-02 16:03 UTC, briandowns approved these changes
LGTM

2021-11-02 19:13 UTC, merged