Added new section for hardened images
rancher/rke2 pull request #2189
Opened 2021-11-30 22:23 UTC by jtravee

Closes #1067

2021-11-30 22:30 UTC, brandond requested changes

2021-11-30 22:30 UTC, brandond commented on docs/security/about_hardened_images.md
> +For any binaries that are written in Go, they are compiled using a FIPS 140-2 compliant build process. For more information on this compiler, refer [here](https://docs.rke2.io/security/fips_support/#
```suggestion
RKE2 hardened images are scanned for vulnerabilities at build time, and additional security protections have been added to decrease potential weaknesses:
* Images are not simply mirrored from upstream builds. The images are built from source on top of a hardened minimal base image, which is currently Red Hat Universal Base Image (UBI).
* Any binaries that are written in Go are compiled using a FIPS 140-2 compliant build process. For more information on this compiler, refer [here](https://docs.rke2.io/security/fips_support/#use-of-fips-compatible-go-compiler).
```

2021-11-30 22:49 UTC, brandond approved these changes

2021-12-02 16:06 UTC, Oats87 approved these changes

2021-12-02 16:08 UTC, merged

2021-12-02 16:08 UTC, dweomer commented on docs/security/about_hardened_images.md
> +Currently, RKE2 hardened images are multi-architecture. Only the Linux AMD64 architecture is FIPS compliant. Windows and the soon-to-come s390x architectures are not FIPS compliant.
```suggestion
Currently, RKE2 hardened images are multi-architecture. Only the Linux AMD64 architecture is FIPS compliant. Windows and the soon-to-come s390x architectures are not yet FIPS compliant.
```
:thinking: /cc @cjellick @Oats87