Added notes on apparmor_parser install
rancher/rke2 pull request #2244
Opened 2021-12-09 18:24 UTC by jtravee

Closes https://github.com/rancher/docs/issues/3651.

Reference: https://docs.rke2.io/install/quickstart/#prerequisites

2021-12-09 19:11 UTC, brandond requested changes

2021-12-09 19:11 UTC, brandond commented on docs/install/quickstart.md
> +    zypper install apparmor-parser
If we're going to document the SLES-specific command we should also document for Ubuntu, which is the other supported distro that ships with AppArmor. Alternately we could just leave it to users to know out how to install a package, which I think is fine.
```suggestion
    zypper install apparmor-parser
```

2021-12-09 19:11 UTC, brandond commented on docs/install/quickstart.md
> +- For RKE2 versions 1.21 and higher, if the host kernel has [AppArmor](https://apparmor.net/), the AppArmor userspace must be present also. You must install the apparmor_parser prior to the RKE2 inst
```suggestion
- For RKE2 versions 1.21 and higher, if the host kernel supports [AppArmor](https://apparmor.net/), the AppArmor tools (usually available via the `apparmor-parser` package) must also be present prior to installing RKE2.
```

2021-12-09 19:30 UTC, jtravee commented on docs/install/quickstart.md
> +- For RKE2 versions 1.21 and higher, if the host kernel has [AppArmor](https://apparmor.net/), the AppArmor userspace must be present also. You must install the apparmor_parser prior to the RKE2 inst
Revised as recommended.

2021-12-09 19:51 UTC, brandond approved these changes

2021-12-10 19:28 UTC, merged

2021-12-22 21:25 UTC, chrisbward commented
https://we.riseup.net/wikis/300095#installing-apparmor-utilities

How does one enable aa in userland?