Rancher/35735 update hardening docs rke2
rancher/rke2 pull request #2507
Opened 2022-02-24 15:36 UTC by macedogm

This is still a **draft** PR to update RKE2's hardening guide.

2022-03-11 09:43 UTC, macedogm commented on docs/security/hardening_guide.md
> +## Host-level requirements
That's a good point. I believe that both ways are correct, it's just a matter of preferences. I'm not a doc writer expert, but I followed some of the recommendations from [SUSE Documentation Style Guide](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-capitalization-sentence). If you believe that it's best to uppercase, then we can do it too.

2022-03-16 18:28 UTC, briandowns commented on docs/security/hardening_guide.md
> +## Host-level requirements
It adheres to the linked style guide so I guess we go with it!

2022-03-16 22:32 UTC, brandond requested changes
One nit, LGTM otherwise!

2022-03-16 22:32 UTC, brandond commented on docs/security/about_hardened_images.md
> +    Currently, RKE2 hardened images are multi-architecture. Only the Linux AMD64 architecture is FIPS compliant. Windows and the soon-to-come s390x architectures are not FIPS compliant.
```suggestion
    Currently, RKE2 hardened images are multi-architecture. Only the Linux AMD64 architecture is FIPS compliant. Windows and s390x are not FIPS compliant.
```

2022-03-17 20:29 UTC, brandond approved these changes

2022-03-18 10:31 UTC, macedogm commented
This PR is ready, but I'm moving to draft in order to hold it's merge, so QA can review it for Rancher 2.6.5 release. CCing @anupama2501 .

2022-04-26 08:59 UTC, macedogm commented
PR is ready to merge, as the review got a green light in https://github.com/rancher/rancher/issues/37242#event-6493743200.

@brandond do we need an additional reviewer/approval?

2022-04-26 20:01 UTC, macedogm commented
@brandond I fixed the spelling error, but the pipeline now failed due to another issue. Doesn't seem to be related to the docs update.

2022-04-28 13:23 UTC, macedogm commented
@brandond pipeline is green now. Can we merge it, please, or do we need another approval?

2022-04-28 14:25 UTC, jossemargt-3pillar approved these changes

2022-06-01 12:25 UTC, macedogm commented
@brandond is the code freeze already lifted? If yes, can we get this PR merged?

2022-06-14 20:27 UTC, dereknola approved these changes

2022-06-14 20:28 UTC, merged