Fix doc inconsistency with --disable flag
rancher/rke2 pull request #2624
Opened 2022-03-17 11:17 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

#### Proposed Changes ####

Fix docs problem:
* rke2-kube-proxy cannot be disabled via the disable flag
* rke2-canal was missing in the list of valid values

#### Types of Changes ####

Docs fix

#### Verification ####

#### Linked Issues ####

https://github.com/rancher/rke2/pull/2036

#### Further Comments ####

2022-03-17 16:20 UTC, briandowns approved these changes

2022-03-17 19:08 UTC, brandond requested changes

2022-03-18 07:01 UTC, manuelbuil commented on docs/install/install_options/server_config.md
> +   --disable value                               (components) Do not deploy packaged components and delete any deployed components (valid items: rke2-coredns, rke2-ingress-nginx, rke2-metrics-server,
that's a good point. I was thinking on the use case where the user deploys without any cni but that's probably a k3s use case

2022-03-18 09:59 UTC, brandond commented on docs/install/install_options/server_config.md
> +   --disable value                               (components) Do not deploy packaged components and delete any deployed components (valid items: rke2-coredns, rke2-ingress-nginx, rke2-metrics-server,
if they do --cni=none then all the CNI charts are added to the list.

2022-03-18 09:59 UTC, brandond approved these changes

2022-03-18 10:55 UTC, merged