March release v1.23.5
rancher/rke2 pull request #2642
Opened 2022-03-17 18:34 UTC by brooksn

#### Proposed Changes ####

Upgrade Kubernetes to v1.23.5

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#2622 

#### Further Comments ####

2022-03-17 18:38 UTC, nikolaishields approved these changes

2022-03-17 18:53 UTC, briandowns commented on developer-docs/upgrading_kubernetes.md
> +* In v1.21, Dockerfile: `RUN CHART_VERSION="v1.21.7-build2021041301"     CHART_FILE=/charts/rke2-kube-proxy.yaml`
```suggestion
* In v1.21, kube-proxy is still in use an needs to be updated in the Dockerfile. Update the line: `RUN CHART_VERSION="v1.21.7-build2021041301"     CHART_FILE=/charts/rke2-kube-proxy.yaml` to the relevant RKE2 Kubernetes build version.
```

2022-03-17 18:56 UTC, briandowns approved these changes

2022-03-17 19:01 UTC, brandond approved these changes

2022-03-22 18:11 UTC, brandond requested changes

2022-03-22 18:11 UTC, brandond commented on Dockerfile
> +RUN CHART_VERSION="2.5.0-rancher101"          CHART_FILE=/charts/rancher-vsphere-csi.yaml CHART_BOOTSTRAP=true   /charts/build-chart.sh
I think there should be changes to https://github.com/rancher/rke2/blob/master/scripts/build-images#L53-L62 for the new images pulled in by this chart update

2022-03-22 18:51 UTC, brandond requested changes

2022-03-22 18:51 UTC, brandond commented on scripts/build-images
> +    ${REGISTRY}/rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.23.0-alpha.1
I believe we're using the 1.22 image, not 1.23 alpha? As per what's in rke2-charts at least:
https://github.com/rancher/rke2-charts/blob/main-source/packages/rancher-vsphere-cpi/generated-changes/patch/values.yaml.patch#L9

2022-03-22 20:40 UTC, merged