ADR, uncheck prerelease last
rancher/rke2 pull request #3192
Opened 2022-07-28 17:15 UTC by matttrach

Signed-off-by: matttrach <matt.trachier@suse.com>

2022-07-28 20:58 UTC, brandond commented
Based on the discussion from the design meeting, lets update this ADR to capture the current interactions between GH releases, the channel server, and downstream tooling such as the install script and System Upgrade Controller. In particular I'd like to make sure we document why the pre-release flag is cleared as soon as all GH artifacts are published and packaging has been tagged.

Also, upon taking a second look at the channel server config, I believe that we should also be clearing the pre-release flag for non-GA releases, as the `testing` channel is set up to specifically include only non-GA tags: https://github.com/rancher/rke2/blob/727b1b1518fa9e4e0cd387f6f16adf018bdd19b6/channels.yaml#L13-L14

Without doing this, we're not honoring the contract of publishing releases to the testing channel.

2022-07-28 21:01 UTC, brandond requested changes
Based on the discussion from the design meeting, lets update this ADR to capture the current interactions between GH releases, the channel server, and downstream tooling such as the install script and System Upgrade Controller. In particular I'd like to make sure we document why the pre-release flag is cleared as soon as all GH artifacts are published and packaging has been tagged.

Also, upon taking a second look at the channel server config, I believe that we should also be clearing the pre-release flag for non-GA releases, as the `testing` channel is set up to specifically include only non-GA tags: https://github.com/rancher/rke2/blob/727b1b1518fa9e4e0cd387f6f16adf018bdd19b6/channels.yaml#L13-L14

Without doing this, we're not honoring the contract of publishing releases to the testing channel.

This makes the pre-release checkbox essentially an indicator that CI is not done yet, removing any residual question around whether or not that flag is used to denote GA releases, and makes the tags the sole indicator of whether a release is GA or not.

2023-01-03 20:55 UTC, nikolaishields approved these changes

2023-03-28 15:22 UTC, matttrach commented
closing this as stale

2023-03-28 15:22 UTC, closed without merging