Build with -tags=netgo to prevent crashes when statically linked
rancher/rke2 pull request #334
Opened 2020-09-17 08:19 UTC by brandond

#### Proposed Changes ####

Build Kubernetes components with -tags=netgo to prevent segfaulting. We're already doing this (static + netgo) for k3s so the same should be safe here.

#### Types of Changes ####

* Build flags
* k3s update

#### Verification ####

* Start rke2
* Note that kubelet no longer crash-loops at 5 second intervals

#### Linked Issues ####

Related to #333

#### Further Comments ####

Also update k3s to master, as the last update apparently didn't get us to the rev we needed to be at to make the agent tunnel controller work with the RBAC changes.

2020-09-17 17:47 UTC, briandowns commented on Dockerfile
> +RUN make KUBE_GIT_VERSION=${TAG} GOLDFLAGS='-extldflags "-static"' GOFLAGS='-tags=netgo' WHAT='cmd/kube-apiserver cmd/kube-controller-manager cmd/kube-proxy cmd/kube-scheduler cmd/kubeadm cmd/kubectl
should have a ref to home dir too

2020-09-17 18:40 UTC, brandond commented on Dockerfile
> +RUN make KUBE_GIT_VERSION=${TAG} GOLDFLAGS='-extldflags "-static"' GOFLAGS='-tags=netgo' WHAT='cmd/kube-apiserver cmd/kube-controller-manager cmd/kube-proxy cmd/kube-scheduler cmd/kubeadm cmd/kubectl
added osusergo

2020-09-17 19:57 UTC, dweomer approved these changes

2020-09-17 19:59 UTC, dweomer commented on Dockerfile
> +RUN make KUBE_GIT_VERSION=${TAG} GOLDFLAGS='-extldflags "-static"' GOFLAGS='-tags="netgo osusergo"' WHAT='cmd/kube-apiserver cmd/kube-controller-manager cmd/kube-proxy cmd/kube-scheduler cmd/kubeadm
```suggestion
RUN make KUBE_GIT_VERSION=${TAG} GOLDFLAGS='-extldflags "-static"' GOFLAGS='-tags "netgo osusergo"' WHAT='cmd/kube-apiserver cmd/kube-controller-manager cmd/kube-proxy cmd/kube-scheduler cmd/kubeadm cmd/kubectl cmd/kubelet vendor/k8s.io/apiextensions-apiserver'
```

2020-09-17 19:59 UTC, dweomer requested changes
build is failing. left suggestion that may fix

2020-09-17 20:28 UTC, brandond commented
Any attempt at quoting or whitespace fails with something like `go: parsing $GOFLAGS: non-flag "\"netgo` regardless of what I use. Seems like something in the makefile or build script is breaking it. I did find a workaround that lets us fail a little later...

2020-09-17 21:57 UTC, brandond commented
This is blocked on https://github.com/rancher/image-build-base/pull/2 - we should be building Kubernetes 1.18 with golang 1.13, not 1.14... so we need to tag a 1.13 release in image-build-base before we can use it here for the image builds.

2020-09-17 23:14 UTC, briandowns approved these changes

2020-09-18 00:06 UTC, dweomer approved these changes

2020-09-18 02:08 UTC, merged