Update documentation with PSP removal
rancher/rke2 pull request #3360
Opened 2022-09-16 20:10 UTC by galal-hussein

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2022-09-16 21:05 UTC, brandond requested changes
A couple nits. There are a bunch of things that are done no matter what the policy flag is set to (as long as its a valid string for that RKE2 release); for those I think we can drop the version language.

2022-09-16 21:05 UTC, brandond commented on docs/security/hardening_guide.md
> +This can be remediated by setting `profile: "cis-1.6"` or `cis-1.23` in newer versions in RKE2 configuration file `/etc/rancher/rke2/config.yaml`. An example can be found below.
```suggestion
This can be remediated by staring RKE2 with the `profile` flag set in the configuration file. An example can be found below.
```

2022-09-16 21:05 UTC, brandond commented on docs/security/hardening_guide.md
> +**v1.25.0 and Higher**
Put 1.25 first

2022-09-16 21:05 UTC, brandond commented on docs/security/pod_security_standards.md
> +!!! NOTE: This document applies to RKE2 versions equal to and after v1.25.0+rke2r1, if you want information for versions below v1.25.0+rke2r1 please refer to the [Default Policies Documentation](poli
```suggestion
!!! NOTE: This document applies to RKE2 version 1.25 and higher, which uses Pod Security Standards. For information on Pod Security Policies present in prior releases, please refer to the [Default Policies Documentation](policies.md).
```

2022-09-16 21:05 UTC, brandond commented on docs/security/pod_security_standards.md
> +Starting from Kubernetes version v1.25.0, PSPs are totally removed from Kubernetes, and replaced by Pod Security Admission. A default Pod SeRKE2 can be ran with or without the `profile: cis-1.23` con
It looks like something got pasted in the middle of an existing sentence here?

2022-09-19 17:04 UTC, cwayne18 commented
@galal-hussein thanks for this! Can you please make sure to fill out the PR template? I'm trying to get better at making sure we're filling them out for every PR

2022-09-20 21:36 UTC, brandond approved these changes

2022-09-20 21:37 UTC, briandowns approved these changes

2022-10-07 14:45 UTC, cwayne18 commented
can we get this landed?

2022-10-13 20:11 UTC, merged