Update fips_support.md
rancher/rke2 pull request #3405
Opened 2022-09-30 20:20 UTC by wjimenez5271

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2022-09-30 20:44 UTC, brandond requested changes

2022-09-30 20:44 UTC, brandond commented on docs/security/fips_support.md
> +This version of Go replaces the standard Go crypto libraries with the FIPS validated BoringCrypto module. See GoBoring's [readme](https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypt
```suggestion
This version of Go replaces the standard Go crypto libraries with the FIPS validated BoringCrypto module. See GoBoring's [readme](https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md) for more details. This module was originally validated by NIST as the [Rancher Kubernetes Cryptographic Library](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3836) in order to ensure support on a wider range of systems. However due to changes introduced by SP 800-56A Rev3, this validation is now historical. A re-validation effort is currently underway to return this module to active FIPS 140-2 status. 
```

2022-09-30 22:05 UTC, brandond requested changes

2022-09-30 22:05 UTC, brandond commented on docs/security/fips_support.md
> +This version of Go replaces the standard Go crypto libraries with the FIPS validated BoringCrypto module. See GoBoring's [readme](https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypt
```suggestion
This version of Go replaces the standard Go crypto libraries with the FIPS validated BoringCrypto module. See GoBoring's [readme](https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md) for more details. This module was originally validated by NIST as the [Rancher Kubernetes Cryptographic Library](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3836) in order to ensure support on a wider range of systems. However due to changes introduced by SP 800-56A Rev3, this validation is now historical. A re-validation effort is currently underway to return this module to active FIPS 140-2 status. 
```

2022-10-03 19:17 UTC, brandond approved these changes

2022-10-03 20:53 UTC, briandowns approved these changes

2022-10-03 22:15 UTC, merged