Add documentation for airgap install
rancher/rke2 pull request #372
Opened 2020-09-25 23:28 UTC by rancher-max

#### Proposed Changes ####
Documentation needed to describe the multiple methods of airgap installations available.

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####
https://github.com/rancher/rke2/issues/281

#### Further Comments ####

2020-09-25 23:38 UTC, brandond requested changes

2020-09-25 23:38 UTC, brandond commented on docs/airgap.md
> +You can either deploy via the bundled system images tar or by using a private registry.
```suggestion
You can either deploy via the bundled `rke2-airgap-images` tarball, or by using a private registry.
```

2020-09-25 23:38 UTC, brandond commented on docs/airgap.md
> +2. Unzip the tar.gz file so that it is only a tar, and add it to `/var/lib/rancher/rke2/agent/images/`.
```suggestion
2. Gunzip the tar.gz file so that it is only a tar, and move it to `/var/lib/rancher/rke2/agent/images/`.
```

2020-09-25 23:38 UTC, brandond commented on docs/airgap.md
> +This requires the private registry to use TLS with the cert trusted by the host OS CA bundle. Furthermore, the registry must not require authentication.
```suggestion
The private registry must be using TLS, with a cert trusted by the host CA bundle. If the registry is using a self-signed cert, you can add the cert to the host CA bundle with `update-ca-certificates`. The registry must also allow anonymous (unauthenticated) access.
```

2020-09-28 22:44 UTC, brandond approved these changes

2020-09-29 15:39 UTC, davidnuzik approved these changes

2020-09-29 15:40 UTC, merged