Updated RKE2 README's header image to point to the new rke2-docs repo
rancher/rke2 pull request #3727
Opened 2022-12-28 23:11 UTC by MaxAnderson95

#### Proposed Changes ####
In PR #3584 the documentation files were moved to their [own separate repo](https://github.com/rancher/rke2-docs). This broke the RKE2 logo on the README.md file. This PR is to change the logo to use the equivalent file in the new repo.

#### Types of Changes ####
Changes to documentation.

#### Verification ####
Render the markdown file and you'll see that it appears as it did before the file was deleted.

#### Linked Issues ####
PR #3584

#### Further Comments ####

2023-01-03 19:13 UTC, nikolaishields approved these changes

2023-01-03 19:28 UTC, brandond requested changes

2023-01-03 19:28 UTC, brandond commented on README.md
> +![RKE2](https://raw.githubusercontent.com/rancher/rke2-docs/a7134bca9cfa6d6d16069313320c9a6dbb3689a4/static/img/logo-horizontal-rke2.svg)
Link to the deployed version, not the version in the repo.
```suggestion
![RKE2](https://docs.rke2.io/img/logo-horizontal-rke2.svg)
```

2023-02-10 17:23 UTC, dereknola approved these changes

2023-02-10 18:07 UTC, brandond approved these changes

2023-02-10 18:45 UTC, merged