Update to v1.23.16
rancher/rke2 pull request #3809
Opened 2023-01-18 22:43 UTC by briandowns

Signed-off-by: Brian Downs <brian.downs@gmail.com>

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2023-01-18 22:45 UTC, brooksn approved these changes

2023-01-18 22:56 UTC, cwayne18 approved these changes

2023-01-18 23:02 UTC, brandond requested changes

2023-01-18 23:02 UTC, brandond commented on Dockerfile
> +FROM rancher/hardened-build-base:v1.19.5b1 AS build
I think there are a couple other references to bump

* https://github.com/rancher/rke2/blob/release-1.23/Dockerfile.windows#L8
* https://github.com/rancher/rke2/blob/release-1.23/.drone.yml#L14 (multiple occurrences in this file)

2023-01-19 00:30 UTC, brandond approved these changes

2023-01-19 00:30 UTC, brandond approved these changes

2023-01-19 00:54 UTC, brooksn approved these changes

2023-01-19 00:59 UTC, merged