Update rke2-killall.sh
rancher/rke2 pull request #4111
Opened 2023-04-12 12:27 UTC by dcasier

#### Proposed Changes ####

prevent line truncating on narrow terminals

#### Types of Changes ####

Bugfix

#### Verification ####

See linked issue

#### Testing ####

#### Linked Issues ####

* https://github.com/rancher/rke2/issues/6024

#### User-Facing Change ####

```
```

#### Further Comments ####

2023-04-12 16:51 UTC, brandond requested changes

2023-04-21 20:24 UTC, brandond approved these changes

2023-04-21 20:25 UTC, brandond commented
Thanks for the PR!

To assist our QA team in validating this fix, can you describe under what circumstances you ran into problems with the killall script being broken by `ps` output line truncation?

2023-04-22 10:33 UTC, dcasier commented
> To assist our QA team in validating this fix, can you describe (preferably in an issue that we can link to this pr) under what circumstances you ran into problems with the killall script being broken by `ps` output line truncation?

In the case of an automated execution of the rke2-uninstall.sh script, the COLUMNS variable can be set to 80.

The path of the binary is truncated, getshims returns nothing and the processes are not killed.

2024-05-28 23:48 UTC, briandowns approved these changes

2024-05-28 23:54 UTC, galal-hussein approved these changes

2024-05-28 23:56 UTC, merged