Add el9 to install script
rancher/rke2 pull request #4256
Opened 2023-05-17 19:56 UTC by galal-hussein

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2023-05-17 19:56 UTC, briandowns approved these changes

2023-05-17 21:10 UTC, brandond requested changes

2023-05-17 21:10 UTC, brandond commented on install.sh
>                  9) # We are currently using EL8 packages for EL9 as well
```suggestion
                9)
```

2023-05-17 21:12 UTC, brandond commented on install.sh
>                  9) # We are currently using EL8 packages for EL9 as well
Actually we don't need this at all. Just take out the whole `9)` case and add 9 to the `7|8)` case up above.

2023-05-23 18:35 UTC, rancher-max commented
https://github.com/rancher/rke2/issues/4285

2023-05-23 21:41 UTC, brandond commented on install.sh
> +    available_upgrades=$(yum -q --refresh list $1 --upgrades | tail -n 1 | awk '{print $2}')
Don't we need to use `${rpm_installer}` for this, not `yum`?

2023-05-24 21:21 UTC, merged