Support new generic "cis" profile
rancher/rke2 pull request #4708
Opened 2023-08-30 16:52 UTC by dereknola

Signed-off-by: Derek Nola <derek.nola@suse.com>

#### Proposed Changes ####
- Add an new `--profile=cis` option that is equivalant  to`cis-1.23`.
- cis-1.23 is now deprecated, begin waring users that it will be removed in v1.29

#### Types of Changes ####
Flag change

#### Verification ####

#### Testing ####

#### Linked Issues ####
https://github.com/rancher/rke2/issues/3645

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-08-30 16:54 UTC, osodracnai approved these changes

2023-08-30 17:01 UTC, vitorsavian approved these changes

2023-08-30 17:02 UTC, brandond reviewed
Nits on excessive formatting

2023-08-30 17:02 UTC, brandond commented on pkg/cli/cmds/root.go
> +				rke2.CISProfile, rke2.CISProfile123+"(deprecated)"),
```suggestion
			Usage: "(security) Validate system configuration against the selected benchmark (valid items: cis, cis-1.23 (deprecated))"),
```

2023-08-31 18:20 UTC, brandond commented on pkg/cli/cmds/root.go
> +			Usage: "(security) Validate system configuration against the selected benchmark (valid items: cis, cis-1.23 (deprecated))"),
did we loose the formatting here? I think `go fmt` would complain about this indentation.

2023-08-31 18:21 UTC, brandond requested changes

2023-08-31 18:21 UTC, brandond commented on pkg/cli/cmds/root.go
> +			Usage: "(security) Validate system configuration against the selected benchmark (valid items: cis, cis-1.23 (deprecated))"),
oh I see.
```suggestion
			Name: "profile",
			Usage: "(security) Validate system configuration against the selected benchmark (valid items: cis, cis-1.23 (deprecated))",
```

2023-09-05 17:45 UTC, brandond approved these changes

2023-09-06 16:27 UTC, merged