[WIP] - Refactor Code to Use K8S Retries
rancher/rke2 pull request #477
Opened 2020-10-08 16:44 UTC by briandowns

## Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#207 

#### Further Comments ####

2020-10-08 16:55 UTC, brandond approved these changes

2020-10-12 17:04 UTC, brandond requested changes

2020-10-12 18:23 UTC, briandowns commented on pkg/rke2/psp.go
> +			if _, err := cs.RbacV1().ClusterRoleBindings().Update(ctx, &clusterRoleBinding, metav1.UpdateOptions{}); err != nil {
Yeah, it was a remnant from testing.

2020-10-12 19:46 UTC, brandond requested changes
Other than this one bit, lgtm

2020-10-12 19:46 UTC, brandond commented on pkg/rke2/psp.go
> +			if _, err := cs.RbacV1().ClusterRoleBindings().Create(ctx, &clusterRoleBinding, metav1.CreateOptions{}); err != nil {
One more bit of err handling simplification

2020-10-12 20:45 UTC, brandond approved these changes

2020-10-13 18:01 UTC, galal-hussein approved these changes
LGTM

2020-10-14 22:53 UTC, brandond approved these changes

2020-10-14 23:35 UTC, dweomer approved these changes

2020-11-04 20:58 UTC, merged