Filter to not accept dependabot and updatecli branchs
rancher/rke2 pull request #4841
Opened 2023-10-04 19:29 UTC by vitorsavian

#### Proposed Changes ####

A filter in `validate-release` to not accept branchs that contains `dependabot` and `updatecli`

#### Types of Changes ####

- Improvement

#### Verification ####

Create a branch with dependabot or update cli in our project
```bash
git checkout -b dependabot/testing
```

Push the branch
```bash
git push origin dependabot/testing
```

See the tag that are in the commit and then use
```bash
git branch --all -q --contains $YOUR_TAG_HERE | grep origin | grep -vE 'dependabot|updatecli' | grep -v origin$ | grep -v "HEAD" | sed -e 's/^[[:space:]]*//'
```

You will not see any dependabot and updatecli branches

#### Testing ####

#### Linked Issues ####

- https://github.com/rancher/rke2/issues/4743

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-10-04 21:38 UTC, brandond requested changes

2023-10-04 21:38 UTC, brandond commented on scripts/validate-release
> +    TAG_BRANCH=$(git branch --all -q --contains $GIT_TAG | grep origin | grep -vE 'dependabot|updatecli' | grep -v origin$ | grep -v "HEAD" | sed -e 's/^[[:space:]]*//')
We've got a bunch of things we're excluding here, maybe combine them?
```suggestion
    TAG_BRANCH=$(git branch --all -q --contains $GIT_TAG | grep origin | grep -vE 'dependabot|updatecli|origin$|HEAD' | sed -e 's/^[[:space:]]*//')
```

2023-10-04 21:51 UTC, brandond approved these changes

2023-10-05 20:00 UTC, briandowns approved these changes

2023-10-05 20:09 UTC, merged