Bump dependencies
rancher/rke2 pull request #4865
Opened 2023-10-10 15:03 UTC by johnatasr

#### Proposed Changes ####

- Bump for Charts
-  Dockerfile images
- build script images

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-10-13 05:58 UTC, brandond approved these changes

2023-10-13 16:34 UTC, dereknola approved these changes

2023-10-16 17:34 UTC, brandond requested changes

2023-10-16 17:34 UTC, brandond commented on scripts/build-windows-binary
> +    -X ${RKE2_PKG}/pkg/images.DefaultEtcdImage=rancher/hardened-etcd:${ETCD_VERSION}-build20231009
Also need to change this in https://github.com/rancher/rke2/blob/45c21222401f736f35c0ceff66db695c195b89a5/scripts/build-binary#L27

2023-10-16 19:08 UTC, briandowns approved these changes

2023-10-16 20:10 UTC, brandond approved these changes
LGTM, please squash before or when merging.

2023-10-16 20:21 UTC, merged

2024-01-02 13:52 UTC, manuelbuil commented
@johnatasr Please note that changes must be backported to previous releases. As far as I see, this PR was never backported to 1.27 and 1.26 branches. Note as well that PRs must always be linked to issues so that QA can verify them