added support for amazon linux 2023
rancher/rke2 pull request #4973
Opened 2023-10-31 04:13 UTC by zackbradys

#### Proposed Changes ####
Propose adding support for Amazon Linux 2023 (AL2023) for Rancher Kubernetes Engine 2 (RKE2). Enabling RKE2 to run on Amazon Linux 2023 will ensure compatibility and increase the adoptability for customers to run RKE2 on AWS.

This pull request includes updates to the RKE2 `install.sh` and `rke2-uninstall.sh` scripts to detect "Amazon Linux 2023" in the operating system identification functions and appropriately configure the installation and uninstallation processes for RKE2 on AL2023. Per Additionally, I noticed not all operating systems were defined, so added them as well.

Documentation Update: PR #0000

#### Types of Changes ####
* **New Feature:** Support Installing RKE2 on Amazon Linux 2023 (AL2023)

#### Verification ####
**Verify Operating System:**
```bash
[root@ip-172-31-43-255 ec2-user]# cat /etc/amazon-linux-release
Amazon Linux release 2023 (Amazon Linux)
```

**Install RKE2 with Updated `install.sh`:**
```bash
[root@ip-172-31-43-255 ec2-user]# curl -sfL https://raw.githubusercontent.com/zackbradys/rke2/master/install.sh | sh
[INFO]  finding release for channel stable
[INFO]  using 1.26 series from channel stable
Rancher RKE2 Common (stable)                                                                       8.6 kB/s | 2.4 kB     00:00    
Rancher RKE2 1.26 (stable)                                                                          19 kB/s | 5.1 kB     00:00    
Dependencies resolved.
===================================================================================================================================
 Package                           Architecture      Version                           Repository                             Size
===================================================================================================================================
Installing:
 rke2-server                       x86_64            1.26.9~rke2r1-0.el8               rancher-rke2-1.26-stable              8.8 k
Installing dependencies:
 container-selinux                 noarch            2:2.222.0-325.amzn2023            amazonlinux                            55 k
 iptables-libs                     x86_64            1.8.8-3.amzn2023.0.2              amazonlinux                           401 k
 iptables-nft                      x86_64            1.8.8-3.amzn2023.0.2              amazonlinux                           183 k
 libnetfilter_conntrack            x86_64            1.0.8-2.amzn2023.0.2              amazonlinux                            58 k
 libnfnetlink                      x86_64            1.0.1-19.amzn2023.0.2             amazonlinux                            30 k
 libnftnl                          x86_64            1.2.2-2.amzn2023.0.2              amazonlinux                            84 k
 rke2-common                       x86_64            1.26.9~rke2r1-0.el8               rancher-rke2-1.26-stable               20 M
 rke2-selinux                      noarch            0.15-1.el8                        rancher-rke2-common-stable             21 k

...

Installed:
  container-selinux-2:2.222.0-325.amzn2023.noarch                iptables-libs-1.8.8-3.amzn2023.0.2.x86_64                        
  iptables-nft-1.8.8-3.amzn2023.0.2.x86_64                       libnetfilter_conntrack-1.0.8-2.amzn2023.0.2.x86_64               
  libnfnetlink-1.0.1-19.amzn2023.0.2.x86_64                      libnftnl-1.2.2-2.amzn2023.0.2.x86_64                             
  rke2-common-1.26.9~rke2r1-0.el8.x86_64                         rke2-selinux-0.15-1.el8.noarch                                   
  rke2-server-1.26.9~rke2r1-0.el8.x86_64                        

Complete!
```

**Enable and Start RKE2 Server:**
```bash
[root@ip-172-31-43-255 ec2-user]# systemctl enable rke2-server && systemctl start rke2-server
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-server.service → /usr/lib/systemd/system/rke2-server.service
```

**Symlink and Update .bashrc:**
```bash
[root@ip-172-31-43-255 ec2-user]# sudo ln -s /var/lib/rancher/rke2/data/v1*/bin/kubectl /usr/bin/kubectl
echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> ~/.bashrc
echo "export PATH=$PATH:/var/lib/rancher/rke2/bin:/usr/local/bin/" >> ~/.bashrc
source ~/.bashrc
```

**Verify RKE2 is Running/Ready:**
```bash
[root@ip-172-31-42-68 ec2-user]# kubectl get nodes
NAME                           STATUS   ROLES                       AGE   VERSION
ip-172-31-42-68.ec2.internal   Ready    control-plane,etcd,master   62s   v1.26.9+rke2r1
```

#### Testing ####

Not all exiting and supported Operating Systems have testing completed. If it helps, I could take a look at adding a test.

#### Linked Issues ####

* **Related RKE2 Issue:** https://github.com/rancher/rke2/issues/4527
* **Related AL2023 Issue:** https://github.com/amazonlinux/amazon-linux-2023/issues/409

#### User-Facing Change ####

```release-note
⚠️ Added support for Amazon Linux 2023 (#0000)
```

#### Further Comments ####
The Rancher Ecosystem and specifically RKE2, already support various distributions of Linux ([see requirements](https://docs.rke2.io/install/requirements#linux)), including others competitors and cloud vendors distributions of Linux. There are many customers who would benefit for being able to use AL2023 or are strictly mandated to only use AL2023 as their operating system and adding native support and validation for AL2023 would be a great enhancement! 

Additionally, we're able to add support for AL2023, without much modification, due to AWS adding support for the latest `container-selinux` package (https://github.com/amazonlinux/amazon-linux-2023/issues/409) in AL2023.

Feedback, suggestions, and input on this proposed change are highly appreciated!

2023-10-31 04:28 UTC, zackbradys commented
#### Additional Verification ####

Specifically with the hardened features of RKE2, such as the DISA STIG, CIS, SELinux, etc...

**Verify Operating System:**
```bash
[root@ip-172-31-40-73 ec2-user]# cat /etc/amazon-linux-release
Amazon Linux release 2023 (Amazon Linux)
```

**Configure Hardened Settings:**
```bash
### Apply System Settings
cat << EOF >> /etc/sysctl.conf
### Modified System Settings
vm.swappiness=0
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
vm.max_map_count = 262144
net.ipv4.ip_local_port_range=1024 65000
net.core.somaxconn=10000
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fin_timeout=15
net.core.somaxconn=4096
net.core.netdev_max_backlog=4096
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_max_syn_backlog=20480
net.ipv4.tcp_max_tw_buckets=400000
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_syn_retries=2
net.ipv4.tcp_synack_retries=2
net.ipv4.tcp_wmem=4096 65536 16777216
net.ipv4.neigh.default.gc_thresh1=8096
net.ipv4.neigh.default.gc_thresh2=12288
net.ipv4.neigh.default.gc_thresh3=16384
net.ipv4.tcp_keepalive_time=600
net.ipv4.ip_forward=1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
fs.inotify.max_user_instances=8192
fs.inotify.max_user_watches=1048576
EOF
sysctl -p > /dev/null 2>&1

### Setup RKE2 Server
mkdir -p /opt/rke2-artifacts/ /etc/rancher/rke2/ /var/lib/rancher/rke2/server/manifests/
useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U

### Configure RKE2 Config
cat << EOF >> /etc/rancher/rke2/config.yaml
profile: cis-1.23
selinux: true
secrets-encryption: true
write-kubeconfig-mode: 0600
use-service-account-credentials: true
kube-controller-manager-arg:
- bind-address=127.0.0.1
- use-service-account-credentials=true
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kube-scheduler-arg:
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kube-apiserver-arg:
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- authorization-mode=RBAC,Node
- anonymous-auth=false
- audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
- audit-log-mode=blocking-strict
- audit-log-maxage=30
kubelet-arg:
- protect-kernel-defaults=true
- read-only-port=0
- authorization-mode=Webhook
- streaming-connection-idle-timeout=5m
pod-security-admission-config-file: /etc/rancher/rke2/rancher-psact.yaml
EOF

### Configure RKE2 Audit Policy
cat << EOF >> /etc/rancher/rke2/audit-policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: RequestResponse
EOF

### Configure RKE2 PSS Pod Security Admissions
cat << EOF >> /etc/rancher/rke2/rancher-psact.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - name: PodSecurity
    configuration:
      apiVersion: pod-security.admission.config.k8s.io/v1
      kind: PodSecurityConfiguration
      defaults:
        enforce: "restricted"
        enforce-version: "latest"
        audit: "restricted"
        audit-version: "latest"
        warn: "restricted"
        warn-version: "latest"
      exemptions:
        usernames: []
        runtimeClasses: []
        namespaces: [calico-apiserver,
                     calico-system,
                     cattle-alerting,
                     cattle-csp-adapter-system,
                     cattle-elemental-system,
                     cattle-epinio-system,
                     cattle-externalip-system,
                     cattle-fleet-local-system,
                     cattle-fleet-system,
                     cattle-gatekeeper-system,
                     cattle-global-data,
                     cattle-global-nt,
                     cattle-impersonation-system,
                     cattle-istio,
                     cattle-istio-system,
                     cattle-logging,
                     cattle-logging-system,
                     cattle-monitoring-system,
                     cattle-neuvector-system,
                     cattle-prometheus,
                     cattle-provisioning-capi-system,
                     cattle-resources-system,
                     cattle-sriov-system,
                     cattle-system,
                     cattle-ui-plugin-system,
                     cattle-windows-gmsa-system,
                     cert-manager,
                     cis-operator-system,
                     fleet-default,
                     fleet-local,
                     ingress-nginx,
                     istio-system,
                     kube-node-lease,
                     kube-public,
                     kube-system,
                     longhorn-system,
                     rancher-alerting-drivers,
                     security-scan,
                     tigera-operator]
EOF
```

**Install RKE2 with Updated `install.sh`:**
```bash
[root@ip-172-31-40-73 ec2-user]# curl -sfL https://raw.githubusercontent.com/zackbradys/rke2/master/install.sh | INSTALL_RKE2_VERSION=v1.25.14+rke2r1 sh
[INFO]  using 1.25 series from channel stable
Rancher RKE2 Common (stable)                                                                               13 kB/s | 2.9 kB     00:00    
Rancher RKE2 1.25 (stable)                                                                                 14 kB/s | 6.6 kB     00:00    
Dependencies resolved.
==========================================================================================================================================
 Package                            Architecture       Version                               Repository                              Size
==========================================================================================================================================
Installing:
 rke2-server                        x86_64             1.25.14~rke2r1-0.el8                  rancher-rke2-1.25-stable               8.8 k
Installing dependencies:
 container-selinux                  noarch             2:2.222.0-325.amzn2023                amazonlinux                             55 k
 iptables-libs                      x86_64             1.8.8-3.amzn2023.0.2                  amazonlinux                            401 k
 iptables-nft                       x86_64             1.8.8-3.amzn2023.0.2                  amazonlinux                            183 k
 libnetfilter_conntrack             x86_64             1.0.8-2.amzn2023.0.2                  amazonlinux                             58 k
 libnfnetlink                       x86_64             1.0.1-19.amzn2023.0.2                 amazonlinux                             30 k
 libnftnl                           x86_64             1.2.2-2.amzn2023.0.2                  amazonlinux                             84 k
 rke2-common                        x86_64             1.25.14~rke2r1-0.el8                  rancher-rke2-1.25-stable                20 M
 rke2-selinux                       noarch             0.15-1.el8                            rancher-rke2-common-stable              21 k

...

Installed:
  container-selinux-2:2.222.0-325.amzn2023.noarch     iptables-libs-1.8.8-3.amzn2023.0.2.x86_64  iptables-nft-1.8.8-3.amzn2023.0.2.x86_64 
  libnetfilter_conntrack-1.0.8-2.amzn2023.0.2.x86_64  libnfnetlink-1.0.1-19.amzn2023.0.2.x86_64  libnftnl-1.2.2-2.amzn2023.0.2.x86_64     
  rke2-common-1.25.14~rke2r1-0.el8.x86_64             [...]

2023-10-31 04:35 UTC, zackbradys commented
#### Additional Verification ####

Verified using new code with existing Terraform Module: https://registry.terraform.io/modules/zackbradys/rke2-cluster

```bash
[root@ip-10-0-40-231 ec2-user]# cat /etc/amazon-linux-release
Amazon Linux release 2023 (Amazon Linux)
```

```bash
[root@ip-10-0-40-231 ec2-user]# kubectl get nodes
NAME                          STATUS   ROLES                       AGE     VERSION
ip-10-0-40-158.ec2.internal   Ready    <none>                      2m35s   v1.25.14+rke2r1
ip-10-0-40-231.ec2.internal   Ready    control-plane,etcd,master   3m5s    v1.25.14+rke2r1
ip-10-0-50-124.ec2.internal   Ready    control-plane,etcd,master   113s    v1.25.14+rke2r1
ip-10-0-50-141.ec2.internal   Ready    <none>                      2m33s   v1.25.14+rke2r1
ip-10-0-60-152.ec2.internal   Ready    control-plane,etcd,master   111s    v1.25.14+rke2r1
ip-10-0-60-242.ec2.internal   Ready    <none>                      2m36s   v1.25.14+rke2r1
```

```bash
[root@ip-10-0-40-231 ec2-user]# kubectl get nodes -o wide
NAME                          STATUS   ROLES                       AGE     VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION                  CONTAINER-RUNTIME
ip-10-0-40-158.ec2.internal   Ready    <none>                      2m39s   v1.25.14+rke2r1   10.0.40.158   <none>        Amazon Linux 2023   6.1.56-82.125.amzn2023.x86_64   containerd://1.7.3-k3s1
ip-10-0-40-231.ec2.internal   Ready    control-plane,etcd,master   3m9s    v1.25.14+rke2r1   10.0.40.231   <none>        Amazon Linux 2023   6.1.56-82.125.amzn2023.x86_64   containerd://1.7.3-k3s1
ip-10-0-50-124.ec2.internal   Ready    control-plane,etcd,master   117s    v1.25.14+rke2r1   10.0.50.124   <none>        Amazon Linux 2023   6.1.56-82.125.amzn2023.x86_64   containerd://1.7.3-k3s1
ip-10-0-50-141.ec2.internal   Ready    <none>                      2m37s   v1.25.14+rke2r1   10.0.50.141   <none>        Amazon Linux 2023   6.1.56-82.125.amzn2023.x86_64   containerd://1.7.3-k3s1
ip-10-0-60-152.ec2.internal   Ready    control-plane,etcd,master   115s    v1.25.14+rke2r1   10.0.60.152   <none>        Amazon Linux 2023   6.1.56-82.125.amzn2023.x86_64   containerd://1.7.3-k3s1
ip-10-0-60-242.ec2.internal   Ready    <none>                      2m40s   v1.25.14+rke2r1   10.0.60.242   <none>        Amazon Linux 2023   6.1.56-82.125.amzn2023.x86_64   containerd://1.7.3-k3s1
```

```bash
[root@ip-10-0-40-231 ec2-user]# rke2-killall.sh
+ systemctl stop rke2-server.service
+ systemctl stop rke2-agent.service
Failed to stop rke2-agent.service: Unit rke2-agent.service not loaded.
+ true
+ killtree 27225 27386 27495 27507 27667 27939 28520 30095 30235 32923
+ kill -9 27225 27245 27277 27386 27407 27439 27495 27540 27603 27507 27542 27605 27667 27688 27719 27939 27959 27991 28520 28541 29260 29336 29344 29337 29338 29341 29339 29342 29340 29345 29669 30095 30137 36200 30235 30284 38580 32923 32943 38811 38823 38855 38861 38862 38863 38864 38865 38866 38867 38868 38870 38900
+ do_unmount_and_remove /run/k3s
+ umount /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f3c3f47782562df74c930660067f5967b6b9c6f16b4998d19815f57c8915aecf/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f1dae6a6ee60fa398fd3edbdd0dd97484cd76c49fcbcc1e0776597ab26bc44c8/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f019691391abfca039f8914acb7be8f69c8b76f3c4d15512bdce883e7f0dcfc1/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/edd63ef37254c0da91821981374c759d8134c35313f9c474fbe4d9c76d8b98fc/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/dea937775dae35a53d8c7419ba521570e3b02a5474a0dee70cf1d8218a45f791/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/de0b0fcb63c1297fbfc1c43f15551c0a0f4adf8ac1a8d442f0781f8e51fe4da0/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/ccd29e13f094229214ae2e42efaae66bbc974c2bc5c19f493594ac57276c72d9/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/c6cd47151a49ff1229118aabf220565a092a7347eec18123fdc07ed236afe769/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/c40aedf78013e599b0d6b1cbb6996af9438918f90eaed21419abeed5dd94abd8/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/aef29eb4498e29928220c443a565267f64b3d65cd6bc985d339a5f580f941450/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/97094c44f035723549eda0d7abc63e646e4d71fded5048507b4e2b357fde7385/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/9505b5a0d764f5daff4591373c7ec0b8194b660299ddb74c68626d106ede5fb9/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/836eddf6d5aacbe0aaa21ffe94483e58c6dc7d1cc2a86b32a8695cfc66a9f9dd/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/47aa96a069bd168f54caa1c2b6a2647cd2fe75c2fabd58b8ba6f273f12f82648/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/400f376a3d0ea35a22c0b33e2bd4d15a314b844ba968f9c179fdf1c01218d685/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/3d42e43b9a330729aac6a80a7fd96f47876b620a7290bf3c63885f9e5abcf8f5/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/34d4c03398cfd9a5d4b1d9f3149f0036d0fbece01f7fca8d6a4f05c3c8c9c4bd/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/206f98cfab0bf2a0fc91889d6fa936f0969a946e0817e36b6391a63dc66c1e0b/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/19a294a01b5a31a875580f872829c0d791491e8dba10ae4626109fec982ddc01/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/043442694c70ccfed5ffb6cd791c0320c08e89ca19da7ff652c9641cf031d2a9/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/001c32ed0a39e537cd183c6c3db9461b8098891ffd9239e4f98a445771f6332e/rootfs /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/f1dae6a6ee60fa398fd3edbdd0dd97484cd76c49fcbcc1e0776597ab26bc44c8/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/dea937775dae35a53d8c7419ba521570e3b02a5474a0dee70cf1d8218a45f791/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/c6cd47151a49ff1229118aabf220565a092a7347eec18123fdc07ed236afe769/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/c40aedf78013e599b0d6b1cbb6996af9438918f90eaed21419abeed5dd94abd8/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/aef29eb4498e29928220c443a565267f64b3d65cd6bc985d339a5f580f941450/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/47aa96a069bd168f54caa1c2b6a2647cd2fe75c2fabd58b8ba6f273f12f82648/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/206f98cfab0bf2a0fc91889d6fa936f0969a946e0817e36b6391a63dc66c1e0b/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/19a294a01b5a31a875580f872829c0d791491e8dba10ae4626109fec982ddc01/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/043442694c70ccfed5ffb6cd791c0320c08e89ca19da7ff652c9641cf031d2a9/shm /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/001c32ed0a39e537cd183c6c3db9461b8098891ffd9239e4f98a445771f6332e/shm
+ rm -rf --one-file-system /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f3c3f47782562df74c930660067f5967b6b9c6f16b4998d19815f57c8915aecf/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f1dae6a6ee60fa398fd3edbdd0dd97484cd76c49fcbcc1e0776597ab26bc44c8/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f019691391abfca039f8914acb7be8f69c8b76f3c4d15512bdce883e7f0dcfc1/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/edd63ef37254c0da91821981374c759d8134c35313f9c474fbe4d9c76d8b98fc/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/dea937775dae35a53d8c7419ba521570e3b02a5474a0dee70cf1d8218a45f791/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/de0b0fcb63c1297fbfc1c43f15551c0a0f4adf8ac1a8d442f0781f8e51fe4da0/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/ccd29e13f094229214ae2e42efaae66bbc974c2bc5c19f493594ac57276c72d9/rootfs /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/c6cd47 [...]

2023-11-27 22:42 UTC, brandond approved these changes

2023-12-12 17:22 UTC, dereknola approved these changes

2023-12-12 17:48 UTC, brandond requested changes
Please restrict these changes to only affecting amazon linux. If we need to change the rocky version detection, we can do that in a different PR.

2023-12-12 17:48 UTC, brandond commented on bundle/bin/rke2-uninstall.sh
> +if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/rocky-release ] [ -r /etc/amazon-linux-release ]; then
```suggestion
if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/amazon-linux-release ]; then
```

2023-12-12 17:48 UTC, brandond commented on bundle/bin/rke2-uninstall.sh
> +    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/rocky-release ] || [ -r /etc/amazon-linux-release ]; then
```suggestion
    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/amazon-linux-release ]; then
```

2023-12-12 17:48 UTC, brandond commented on install.sh
> +    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/rocky-release ] || [ -r /etc/amazon-linux-release ] || [ "${ID_LIKE%%[ ]*}" = "suse"  ]; the
```suggestion
    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/amazon-linux-release ] || [ "${ID_LIKE%%[ ]*}" = "suse"  ]; then
```

2023-12-12 17:48 UTC, brandond commented on install.sh
> +                7|8|9) # detect centos distro
```suggestion
                7|8|9)
```

2023-12-12 17:49 UTC, dereknola requested changes

2023-12-12 17:49 UTC, dereknola commented on bundle/bin/rke2-uninstall.sh
> +    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/rocky-release ] || [ -r /etc/amazon-linux-release ]; then
Please remove section on rocky release. QA does not have bandwidth to validate changes to rocky installs this release cycle so we want to restrict the scope of this PR.
```suggestion
    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/amazon-linux-release ]; then
```

2023-12-12 17:49 UTC, dereknola commented on install.sh
> +    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/rocky-release ] || [ -r /etc/amazon-linux-release ] || [ "${ID_LIKE%%[ ]*}" = "suse"  ]; the
Please remove section on rocky release. QA does not have bandwidth to validate changes to rocky installs this release cycle so we want to restrict the scope of this PR.
```suggestion
    if [ -r /etc/redhat-release ] || [ -r /etc/centos-release ] || [ -r /etc/oracle-release ] || [ -r /etc/amazon-linux-release ] || [ "${ID_LIKE%%[ ]*}" = "suse"  ]; then
```

2023-12-12 18:50 UTC, brandond approved these changes

2023-12-12 19:12 UTC, dereknola approved these changes

2023-12-12 21:52 UTC, rancher-max approved these changes
LGTM -- Thank you for this! I'm okay with merging this now but it might not be fully QA'ed during the December patches, so support at this time should be considered "experimental"

2023-12-13 00:01 UTC, brandond commented
Merging with Max's approval.

2023-12-13 00:01 UTC, merged

2023-12-13 00:14 UTC, zackbradys commented
Thank you for the review and validation! @brandond @dereknola

Understand the need for additional QA and experimental status. I appreciate the approval and merge. @rancher-max