[wip] enable k3s cloud provider if node-external-ip flag is passed to rke2
rancher/rke2 pull request #506
Opened 2020-10-27 20:22 UTC by MonzElmasry

#### Linked Issues ####

https://github.com/rancher/rke2/issues/309

2020-10-27 20:51 UTC, MonzElmasry commented
progress is blocked by https://github.com/rancher/k3s/issues/2345

2020-10-29 20:52 UTC, brandond requested changes

2020-10-29 20:52 UTC, brandond commented on Dockerfile
> +COPY manifests/ccm.yaml /manifests/
We are not packaging roles and such as manifest files for rke2. The only thing we deploy should be helm charts. If you need to add RBAC it should be added in here somewhere: https://github.com/rancher/rke2/blob/master/pkg/rke2/clusterrole_templates.go

2020-10-30 22:34 UTC, dweomer approved these changes

2020-10-30 23:53 UTC, brandond approved these changes

2020-10-31 00:15 UTC, merged

2021-01-29 11:09 UTC, fentas commented
Thanks :+1: 
Documentation for this is still missing, though.

2021-01-29 18:17 UTC, brandond commented
@fentas what are you looking for documentation on?

2021-01-29 19:47 UTC, fentas commented
https://docs.rke2.io/install/install_options/server_config/

`node-external-ip` is not documented here as a parameter. : )