Enable arm64 based cilium images
rancher/rke2 pull request #5154
Opened 2023-12-21 17:04 UTC by mgfritch

Also removes deprecated `cilium-etcd-operator`

Linked issue: https://github.com/rancher/rke2/issues/5136

2023-12-21 18:46 UTC, brandond approved these changes

2023-12-22 10:26 UTC, thomasferrandiz approved these changes

2024-01-02 10:09 UTC, manuelbuil approved these changes

2024-01-12 22:49 UTC, brandond requested changes
nit: this is also enabling arm64 for calico, multus, vsphere, and harvester. Either make sure that those all exist, or keep them excluded from this arch.

Also, if you keep those included, update the PR title and description to make it clear that we're doing more than just cilium here.

2024-01-12 23:37 UTC, brandond approved these changes

2024-01-12 23:40 UTC, merged