fix: missing 'ip link delete cilium_wg0' in rke2-killall.sh
rancher/rke2 pull request #5274
Opened 2024-01-15 10:32 UTC by faelis

#### Proposed Changes ####

 The network interface 'cilium_wg0' (added when wireguard is enabled in cilium) is not removed by the rke2-killall.sh script.

#### Types of Changes ####

Bugfix

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-01-15 14:49 UTC, manuelbuil requested changes
Thanks for the fix! Could you please:
* Add the line in `dist/bundle/bin/rke2-killall.sh` too
* Fill an issue in rke2 with "bug fix" type. Then link the issue to the PR

Thanks!

2024-01-16 09:20 UTC, faelis commented
Hi @manuelbuil ! thanks for the review. Just added the linked issue.
But I didn't find the `dist/bundle/bin/rke2-killall.sh` in the rke2 project, can you help me?

2024-01-16 09:30 UTC, manuelbuil commented
> Hi @manuelbuil ! thanks for the review. Just added the linked issue. But I didn't find the `dist/bundle/bin/rke2-killall.sh` in the rke2 project, can you help me?

Sorry! Stupid me, that gets created when building RKE2

2024-01-16 09:30 UTC, manuelbuil approved these changes

2024-01-16 09:31 UTC, manuelbuil commented
I have a comment in the issue.

BTW, we are under code freeze right now for the January release. I you get two positive reviews, we will merge after code freeze and this PR will be part of the February release

2024-01-16 10:08 UTC, faelis commented
I added the missing configuration in the issue

2024-02-09 07:55 UTC, rbrtbnfgl approved these changes

2024-02-09 08:14 UTC, merged