Bump ingress-nginx to 1.9.6
rancher/rke2 pull request #5671
Opened 2024-04-03 21:00 UTC by dereknola

Signed-off-by: Derek Nola <derek.nola@suse.com>

#### Proposed Changes ####
- Hardened nginx bump

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####
TBD

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-04-03 23:43 UTC, brandond requested changes
Doesn't the chart need to be changed first?

2024-04-04 00:06 UTC, dereknola commented
https://github.com/rancher/rke2-charts/pull/431 is Already merged

2024-04-04 00:15 UTC, brandond commented
right but this PR only bumps the image, not the chart

2024-04-04 16:29 UTC, brandond approved these changes

2024-04-08 16:28 UTC, merged