Fix Networking anchor
rancher/rke2 pull request #576
Opened 2020-12-08 04:40 UTC by jenting

#### Proposed Changes ####

Remove Klipper service LB from content and correct the anchors.

#### Types of Changes ####

Fix doc.

#### Verification ####

N/A

#### Linked Issues ####

N/A

#### Further Comments ####

N/A

2020-12-09 07:19 UTC, brandond requested changes

2020-12-09 07:19 UTC, brandond commented on docs/networking.md
> +This page explains how CoreDNS, the Nginx-Ingress controller work within RKE2.
```suggestion
This page explains how CoreDNS and the Nginx-Ingress controller work within RKE2.
```

2020-12-09 08:27 UTC, brandond approved these changes

2020-12-29 17:44 UTC, briandowns approved these changes

2020-12-29 17:45 UTC, merged