Document no grade path from RKE
rancher/rke2 pull request #579
Opened 2020-12-09 03:49 UTC by c3y1huang

#### Proposed Changes ####

https://github.com/rancher/rke2/issues/488.

#### Types of Changes ####

Document

#### Verification ####

`none`

#### Linked Issues ####

https://github.com/rancher/rke2/issues/488
https://github.com/rancher/rke2/issues/562

#### Further Comments ####

`none`

2020-12-09 03:55 UTC, briandowns approved these changes

2020-12-09 07:01 UTC, brandond requested changes

2020-12-09 07:01 UTC, brandond commented on docs/index.md
> +But our next phase of development will focus on a seamless upgrade path and feature parity with RKE1 when integrated with the Rancher multi-cluster management platform.
```suggestion
## Can I upgrade from RKE1 to RKE2?

Currently, we do not support upgrades from RKE1 or K3s to RKE2.

Our next phase of development will focus on a seamless upgrade path and feature parity with RKE1, when integrated with the Rancher multi-cluster management platform.
```

2020-12-09 07:45 UTC, c3y1huang commented on docs/index.md
> +But our next phase of development will focus on a seamless upgrade path and feature parity with RKE1 when integrated with the Rancher multi-cluster management platform.
Addressed.

2020-12-09 08:26 UTC, brandond approved these changes

2021-09-13 20:20 UTC, closed without merging

2021-09-13 20:21 UTC, cwayne18 commented
Thank you for the PR, but there actually will now be a path to upgrade from rke->rke2 using migration-agent, so closing this out.