Add mixedos BGP e2e test
rancher/rke2 pull request #5859
Opened 2024-04-29 07:17 UTC by manuelbuil

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-04-29 08:34 UTC, thomasferrandiz approved these changes

2024-04-29 21:05 UTC, dereknola requested changes
you need to change the name of the test folder to `mixedosbgp`, it must match the test name prefix. Or change both to be `mixedos_bgp`... we don't use dashes for the testing names.

2024-04-30 07:03 UTC, rbrtbnfgl commented
Maybe you need to add `Restart-Service RemoteAccess` somewhere on the script after RKE2 started on windows because it could happen that the BGP configuration is not rightly taken by the service. i don't know if it has been fixed in Calico.

2024-04-30 09:51 UTC, manuelbuil commented
> Maybe you need to add `Restart-Service RemoteAccess` somewhere on the script after RKE2 started on windows because it could happen that the BGP configuration is not rightly taken by the service. i don't know if it has been fixed in Calico.

The test was working in my computer, maybe it is not needed anymore

2024-04-30 16:27 UTC, dereknola approved these changes

2024-04-30 16:43 UTC, brandond approved these changes

2024-05-02 05:21 UTC, merged