update code and docs to use and reference v1.18.13 respectively
rancher/rke2 pull request #587
Opened 2020-12-10 21:53 UTC by briandowns

#### Proposed Changes ####

Update code and docs to use and reference v1.18.13 respectively.

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2020-12-10 21:56 UTC, brandond requested changes

2020-12-10 21:56 UTC, brandond commented on contrib/custom-image-kubelet/README.md
> +1. RKE2 v1.18.13-beta1+rke2r2 or newer (with image/kubelet override support)
I know this was probably just caught by sed, but we might as well bump to full GA release
```suggestion
1. RKE2 v1.18.13+rke2r1 or newer (with image/kubelet override support)
```

2020-12-10 21:56 UTC, brandond commented on contrib/custom-image-kubelet/README.md
> +curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.18.13-beta1+rke2r2 sh -
```suggestion
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.18.13+rke2r1 sh -
```

2020-12-10 23:16 UTC, brandond approved these changes

2020-12-11 18:41 UTC, MonzElmasry approved these changes

2020-12-11 18:42 UTC, Oats87 approved these changes

2020-12-11 19:45 UTC, merged