Add e2e test about mixedos+flannel
rancher/rke2 pull request #6063
Opened 2024-05-30 11:15 UTC by manuelbuil

#### Proposed Changes ####

New e2e test

#### Types of Changes ####

New test

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-05-30 16:47 UTC, dereknola requested changes
Can you merge the two `mixedos` e2e test together, and just have CNI be a variable similar to https://github.com/rancher/rke2/blob/master/tests/e2e/validatecluster/Vagrantfile#L10?

2024-05-30 18:50 UTC, brandond approved these changes

2024-05-31 09:37 UTC, manuelbuil commented
> Can you merge the two `mixedos` e2e test together, and just have CNI be a variable similar to https://github.com/rancher/rke2/blob/master/tests/e2e/validatecluster/Vagrantfile#L10?

As long as @ShylajaDevadiga can confirm that we can change that variable in her scripts to run https://rke2-results.s3.us-east-2.amazonaws.com/rke2_ubuntu2004_results.html, then yes :)

2024-06-26 15:11 UTC, dereknola approved these changes

2024-07-09 13:14 UTC, thomasferrandiz approved these changes

2024-07-10 06:25 UTC, merged