Update calico image to v3.28.0-build20240625
rancher/rke2 pull request #6257
Opened 2024-06-25 23:56 UTC by galal-hussein

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-06-26 00:11 UTC, briandowns approved these changes

2024-06-26 02:17 UTC, brandond approved these changes

2024-06-26 17:34 UTC, brandond requested changes

2024-06-26 17:34 UTC, brandond commented on scripts/build-images
>      ${REGISTRY}/rancher/hardened-flannel:v0.25.3-build20240605
The flannel version here needs to be bumped as well - `v3.28.0-build2024062502`  included a flannel bump but wasn't ever pulled through.
```
[[36mBASICS[m] -docker.io/rancher/hardened-flannel:v0.25.3-build20240605
[[36mBASICS[m] +docker.io/rancher/hardened-flannel:v0.25.4-build20240610
```

```suggestion
    ${REGISTRY}/rancher/hardened-flannel:v0.25.4-build20240610
```

2024-06-28 16:59 UTC, brandond approved these changes

2024-06-28 18:54 UTC, merged