[release-1.28] Update calico image to v3.28.0-build20240625
rancher/rke2 pull request #6259
Opened 2024-06-25 23:57 UTC by galal-hussein

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-06-26 00:11 UTC, briandowns approved these changes

2024-06-26 17:39 UTC, brandond requested changes

2024-06-26 17:39 UTC, brandond commented on scripts/build-images
>      ${REGISTRY}/rancher/hardened-flannel:v0.25.3-build20240605
https://github.com/rancher/rke2/pull/6257#discussion_r1655278323

2024-06-28 17:00 UTC, brandond approved these changes

2024-06-28 18:53 UTC, merged