[Release-1.28] GHA Migration (#6062)
rancher/rke2 pull request #6294
Opened 2024-07-09 21:09 UTC by galal-hussein

2024-07-09 23:41 UTC, brandond requested changes

2024-07-09 23:41 UTC, brandond commented on Dockerfile.windows
> +RUN mv CalicoWindows/cni/calico.DAPPER_ENV GODEBUG REPO TAG DRONE_TAG PAT_USERNAME PAT_TOKEN KUBERNETES_VERSION DOCKER_BUILDKIT DRONE_BUILD_EVENT IMAGE_NAME AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID EN
what's going on here?

2024-07-09 23:57 UTC, galal-hussein commented on Dockerfile.windows
> +RUN mv CalicoWindows/cni/calico.DAPPER_ENV GODEBUG REPO TAG DRONE_TAG PAT_USERNAME PAT_TOKEN KUBERNETES_VERSION DOCKER_BUILDKIT DRONE_BUILD_EVENT IMAGE_NAME AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID EN
Just vscode being an idiot with resolving conflicts

2024-07-10 00:09 UTC, brandond approved these changes

2024-07-10 00:37 UTC, briandowns approved these changes

2024-07-12 18:56 UTC, merged