Add `data-dir` to uninstall and killall scripts
rancher/rke2 pull request #6296
Opened 2024-07-09 21:17 UTC by jakefhyde

#### Proposed Changes ####

Add `RKE2_DATA_DIR` as an optional environment variable to the `rke2-killall.sh`,`rke2-uninstall.sh`, and `rke2-uninstall.ps1` scripts.

#### Types of Changes ####

Bugfix

#### Verification ####

Installing RKE2 with a custom `data-dir` (not `/var/lib/rancher/rke2`), and running the killall and uninstall scripts, verifying assets in `/var/lib/rancher/rke2` are properly removed.

#### Testing ####

This is not currently covered by testing, though I would be happy to write an integration test if need be.

#### Linked Issues ####

* https://github.com/rancher/rke2/issues/6292

#### User-Facing Change ####

```release-note
NONE
```

#### Further Comments ####

Relates to https://github.com/rancher/rancher/issues/46066.

2024-07-09 21:26 UTC, brandond requested changes

2024-07-09 21:26 UTC, brandond commented on bundle/bin/rke2-killall.sh
> +      "${POD_MANIFESTS_DIR}/cloud-controller-manager.yam"l\
```suggestion
      "${POD_MANIFESTS_DIR}/cloud-controller-manager.yaml" \
```

2024-07-10 00:50 UTC, brandond approved these changes

2024-07-10 05:32 UTC, manuelbuil approved these changes

2024-07-10 17:20 UTC, merged