[Release-1.31] Update cilium chart to `1.16.103`
rancher/rke2 pull request #6714
Opened 2024-09-04 15:53 UTC by mgfritch

Backport: https://github.com/rancher/rke2/pull/6707
Issue: https://github.com/rancher/rke2/issues/6710

2024-09-04 15:54 UTC, thomasferrandiz approved these changes

2024-09-04 17:55 UTC, brandond requested changes
needs images update

2024-09-05 05:41 UTC, mgfritch commented
> needs images update. It looks like all the other branches got bumped to 102 of the chart with the corresponding images update. Did that get missed on this branch, or does it just need to be merged first and then this PR rebased?

Sorry, I should have made this more clear. I've rebased this against https://github.com/rancher/rke2/pull/6700 and we are waiting for the branch to unfreeze before merging both PRs.

2024-09-09 17:03 UTC, brandond approved these changes

2024-09-09 18:44 UTC, merged