update audit docs
rancher/rke2 pull request #701
Opened 2021-02-16 18:25 UTC by galal-hussein

#### Linked Issues ####

https://github.com/rancher/rke2/issues/685

2021-02-26 20:50 UTC, brandond approved these changes

2021-03-01 15:26 UTC, davidnuzik requested changes

2021-03-01 15:26 UTC, davidnuzik commented on docs/security/hardening_guide.md
> +RKE2 supports configuring audit logging by passing --profile=cis-1.5, it enables a default policy which doesn't log anything, to configure a customize policy you should pass --audit-policy-file argum
```suggestion
RKE2 supports configuring audit logging by passing `--profile=cis-1.5`. It enables a default policy which doesn't log anything. To configure a customize policy, you should pass the `--audit-policy-file` argument to the RKE2 server process. This argument specifies the path for audit logging policy configuration. For more information about the logging policy, you can checkout the [official docs](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy).
```

2021-03-01 23:39 UTC, davidnuzik approved these changes

2021-03-01 23:39 UTC, davidnuzik commented
LGTM, thanks! I will go ahead and merge this now.

2021-03-01 23:39 UTC, merged