Update docs for node-password
rancher/rke2 pull request #735
Opened 2021-02-27 00:15 UTC by erikwilson

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####
For https://github.com/rancher/rke2/issues/617

#### Further Comments ####

2021-02-27 00:26 UTC, brandond requested changes

2021-02-27 00:26 UTC, brandond commented on docs/advanced.md
> +If the `/etc/rancher/node` directory of an agent is removed, the password file should be recreated for the agent, or the entry removed from the server.
A few minor wording nits:
```suggestion
Agent nodes are registered via a websocket connection initiated by the `rke2 agent` process, and the connection is maintained by a client-side load balancer running as part of the agent process.

Agents register with the server using the cluster secret portion of the join token, along with a randomly generated node-specific password, which is stored on the agent at `/etc/rancher/node/password`. The server will store the passwords for individual nodes as Kubernetes secrets, and any subsequent attempts must use the same password. Node password secrets are stored in the `kube-system` namespace with names using the template `<host>.node-password.rke2`. These secrets are deleted when the corresponding Kubernetes node is deleted.

Note: Prior to RKE2 v1.20.2 servers stored passwords on disk at `/var/lib/rancher/rke2/server/cred/node-passwd`.

If the `/etc/rancher/node` directory of an agent is removed, the password file should be recreated for the agent prior to startup, or the entry removed from the server or Kubernetes cluster (depending on the RKE2 version).
```

2021-03-01 18:03 UTC, brandond approved these changes

2021-03-02 17:19 UTC, dweomer approved these changes

2021-03-02 18:12 UTC, merged