[WIP] Add runtime classes hook and runtimes chart
rancher/rke2 pull request #7382
Opened 2024-12-03 23:48 UTC by vitorsavian

#### Proposed Changes ####

- Fix for runtimes class chart not being used
- Add a hook for ownership of runtime classes that rke2 supports

#### Types of Changes ####

- Bugfix

#### Verification ####

#### Testing ####

#### Linked Issues ####

- https://github.com/rancher/rke2/issues/7242

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-12-04 00:05 UTC, brandond requested changes

2024-12-04 00:05 UTC, brandond commented on pkg/rke2/rc.go
> +			}
We should probably fix this in the other files in pkg/rke2 as well - but you can use https://github.com/k3s-io/k3s/blob/master/pkg/util/client.go#L30
```suggestion
			client, err := util.GetClientSet(args.KubeConfigSupervisor)
			if err != nil {
				logrus.Fatalf("runtimes: new k8s client: %v", err)
			}
```

2024-12-04 00:05 UTC, brandond commented on pkg/rke2/rc.go
> +					c.SetLabels(labels)
You don't need to use the helper, you can just do what we do everywhere else:
```suggestion
					c.Labels = map[string]string{}
```

2024-12-04 00:05 UTC, brandond commented on pkg/rke2/rc.go
> +					c.SetAnnotations(annotations)
```suggestion
					c.Annotations = map[string]string{}
```

2024-12-04 00:05 UTC, brandond commented on pkg/rke2/rc.go
> +					c.Annotations["meta.helm.sh/release-name"] = runtimeClassesChart
could probably add consts for the helm label and annotations keys

2024-12-04 01:23 UTC, brandond commented on pkg/rke2/rc.go
> +	helmReleaseNamespace = "meta.helm.sh/release-namespace"
I would probably use the same consts as upstream: https://github.com/helm/helm/blob/main/pkg/action/validate.go#L33-L38
```suggestion
	appManagedByLabel              = "app.kubernetes.io/managed-by"
	appManagedByHelm               = "Helm"
	helmReleaseNameAnnotation      = "meta.helm.sh/release-name"
	helmReleaseNamespaceAnnotation = "meta.helm.sh/release-namespace"
```

2024-12-04 03:59 UTC, brandond commented on pkg/rke2/rc.go
> +	defaultNamespace    = "kube-system"
You don't need this, also it's not correct (as this is the system namespace, not default) - use the existing const `metav1.NamespaceSystem`

2024-12-04 19:26 UTC, brandond approved these changes

2025-01-10 18:39 UTC, matttrach approved these changes

2025-01-13 12:17 UTC, merged