Update k3s to bring in cluster reset flag
rancher/rke2 pull request #882
Opened 2021-04-14 23:00 UTC by briandowns

Signed-off-by: Brian Downs <brian.downs@gmail.com>

#### Proposed Changes ####

Update k3s to bring in cluster reset flag

#### Types of Changes ####

#### Verification ####

```sh
rke2 server -h | grep 'cluster-reset'
```

#### Linked Issues ####

#856 

#### Further Comments ####

2021-04-14 23:08 UTC, galal-hussein approved these changes

2021-04-14 23:29 UTC, brandond requested changes

2021-04-14 23:29 UTC, brandond commented on go.mod
> +	github.com/rancher/k3s 66ed6efd57768e29885448c0e6be5de127eb47a8
`go mod tidy`

2021-04-14 23:36 UTC, briandowns commented on go.mod
> +	github.com/rancher/k3s 66ed6efd57768e29885448c0e6be5de127eb47a8
All set.

2021-04-15 00:05 UTC, brandond approved these changes

2021-04-15 00:41 UTC, merged